version: "3.3"

services:
  neo4j:
    image: neo4j:latest
    ports:
      - "7687:7687"
    volumes:
      - ./data:/data    

  be-service:
    build:
      context: .
    image: neo4j-be-service:latest
    ports:
      - "8080:8080"
    depends_on:
      - neo4j
