name: Adaptive training CI

on:
  push:
    branches:
      - '**'  # Trigger on all branches
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_CLI_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/.m2/repository"
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install $MAVEN_CLI_OPTS -DskipTests -Dproprietary-repo-url=${{ vars.PROPRIETARY_REPO_URL }}
        env:
          PROPRIETARY_REPO_URL: ${{ vars.PROPRIETARY_REPO_URL }}

  tests:
    runs-on: ubuntu-latest
    needs: build
    env:
      MAVEN_CLI_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/.m2/repository"
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Run tests
        run: mvn test $MAVEN_CLI_OPTS -Dproprietary-repo-url=${{ vars.PROPRIETARY_REPO_URL }}
        env:
          PROPRIETARY_REPO_URL: ${{ vars.PROPRIETARY_REPO_URL }}

  generate_docs:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Generate and Push Swagger Docs
        run: |
          mvn clean package $MAVEN_CLI_OPTS -DskipTests -Dswagger.skip=false -Dproprietary-repo-url=${{ vars.PROPRIETARY_REPO_URL }}
          ls -la
        #if: github.ref == 'refs/heads/master'

      - name: Upload Docs Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.repository }}-docs
          path: doc-files/kypo-adaptive-training-swagger-open-api.yaml

# Additional stages/jobs (create_tag, generate_docs, docker_image_push, etc.) 
# can be added here following the same pattern.
