name: Adaptive training CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  MAVEN_CLI_OPTS: "-Dmaven.repo.local=${{ github.workspace }}/.m2/repository"

jobs:
  java_template:
    uses: cyberrangecz/actions-templates/.github/workflows/java_template.yml@master
    with:
      MAVEN_CLI_OPTS: $MAVEN_CLI_OPTS

  create_tag:
    uses: cyberrangecz/actions-templates/.github/workflows/tag_template.yml@master
    with:
      VERSION: ${{ vars.VERSION }}
